### ISSUE TITLE
Not hide warnings from inspections

### ISSUE THREAD

**Issue by cheptsov** [cheptsov/AdvancedExpressionFolding#22]

**Comment by nathanmbrown** [comment]
Compilation errors are also hidden, let me know if you'd rather this be under a separate ticket?

**Comment by cheptsov** [comment]
https://youtrack.jetbrains.com/issue/IDEA-61533

**Comment by bvn13** [comment]
+1 have this issue too

**Comment by ciscorucinski** [comment]
Looks like this issue is going to be fixed in 2018.1. The issue was just updated by JetBrains. Next update should have this fix. Watch for it

@bvn13 @nathanmbrown @cheptsov 

https://youtrack.jetbrains.com/issue/IDEA-61533

**Comment by cheptsov** [comment]
Now it should work with v2018.1 EAP.
